name: ray-serve-tutorial
channels:
  - conda-forge
  - defaults
dependencies:
- python=3.7.13 # need to match version of python in AKS runtime to be able to run with 'serve run' directly into AKS
- pip
- pip:
  - ipykernel
  - python-dotenv
  - ray[serve]
  - starlette
  - torch
  - transformers